// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// scrambler_Cpp
RawMatrix scrambler_Cpp(RawMatrix arr, int nchunks);
RcppExport SEXP _imageScrambleR_scrambler_Cpp(SEXP arrSEXP, SEXP nchunksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawMatrix >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< int >::type nchunks(nchunksSEXP);
    rcpp_result_gen = Rcpp::wrap(scrambler_Cpp(arr, nchunks));
    return rcpp_result_gen;
END_RCPP
}
// scrambler_Cpp2
RawMatrix scrambler_Cpp2(RawMatrix arr, int nchunks);
RcppExport SEXP _imageScrambleR_scrambler_Cpp2(SEXP arrSEXP, SEXP nchunksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawMatrix >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< int >::type nchunks(nchunksSEXP);
    rcpp_result_gen = Rcpp::wrap(scrambler_Cpp2(arr, nchunks));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_imageScrambleR_scrambler_Cpp", (DL_FUNC) &_imageScrambleR_scrambler_Cpp, 2},
    {"_imageScrambleR_scrambler_Cpp2", (DL_FUNC) &_imageScrambleR_scrambler_Cpp2, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_imageScrambleR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
